823 update locations and holdings
pulibrary/marc_liberation pull request #1033
Opened 2021-02-02 00:44 UTC by christinach

2021-02-02 18:19 UTC, christinach commented
I'm looking for an oversize holding id in Alma. @mzelesky said I can find one by looking for an 852 | k of 'Oversize'.

2021-02-02 18:20 UTC, christinach commented
https://github.com/pulibrary/marc_liberation/pull/1033#issuecomment-771861761 This is to satisfy the process_holdings spec.

2021-02-03 22:30 UTC, christinach commented on spec/marc_to_solr/lib/princeton_marc_spec.rb
>      it 'includes first instance of 852 $t as copy_number' do
Is this still valid? To include the first instance of 852 $t as copy_number? The fixture I'm testing doesn't have a $t in the first 852. The code in https://github.com/pulibrary/marc_liberation/blob/cda1e2ce5466224748e6a74eab5ae55553faa059/marc_to_solr/lib/princeton_marc.rb#L653 doesn't check something like that. Do I want to update it or keep it as it is?

2021-02-03 22:31 UTC, christinach commented on spec/marc_to_solr/lib/princeton_marc_spec.rb
>      end
ok, I'm guessing the answer for https://github.com/pulibrary/marc_liberation/pull/1033/files#r569797757 is here. But I still want to confirm with @mzelesky .

2021-02-03 22:33 UTC, christinach commented on spec/marc_to_solr/lib/princeton_marc_spec.rb
>      end
I need to update the code it adds 852|c in the call_number. In this case it adds 'stacks M23.L5S6 1973q Oversize'

2021-02-04 20:32 UTC, christinach commented on spec/marc_to_solr/lib/princeton_marc_spec.rb
>      it 'includes first instance of 852 $t as copy_number' do
I will update this. In the checkin @mzelesky reminded me that the copy_number is part of the items now.

2021-02-15 15:38 UTC, hackartisan requested changes
@tpendragon and I looked at this together and left a couple of comments. Otherwise, I'd like to try it out locally; just need to get set up indexing to a local orangelight.

2021-02-15 18:48 UTC, hackartisan commented
@christinach this will need to be rebased on the alma branch, since Monday happened.

I tried it out and I see a bunch of holdings locations coming through. I also see a bunch that say "no holdings available for this record". I'm not sure what those mean. But this does seem like progress! Here's a screenshot from my local orangelight:

![Screen Shot 2021-02-15 at 1 46 35 PM](https://user-images.githubusercontent.com/845363/107983772-7f81fb80-6f94-11eb-9f16-8e351e980c5b.png)

2021-02-17 14:47 UTC, christinach commented
@hackartisan thanks. Will do.

2021-02-17 15:29 UTC, christinach commented on marc_to_solr/lib/princeton_marc.rb
> +    all_holdings[holding_id] = holding unless holding_id.nil? || (!is_alma && invalid_location?(holding['location_code']))
@hackartisan  @tpendragon  The `is_alma` is checking if it is a valid princeton record. If we are positive that the records we have in the production box are all valid princeton records, I can remove the `is_alma` check. I don't understand how this is related to 'so we do want to make sure the location is valid'.

2021-02-17 15:37 UTC, christinach commented on marc_to_solr/lib/princeton_marc.rb
>          unless s_field.code == 'c'
yes, sorry about that. I updated the subfields for the call_number and removed c from the match, but overlooked the unless branch. I will remove it.

2021-02-17 15:45 UTC, christinach commented on marc_to_solr/lib/princeton_marc.rb
> +    all_holdings[holding_id] = holding unless holding_id.nil? || (!is_alma && invalid_location?(holding['location_code']))
oh sorry now I see the exact line! yes I will remove it from `all_holdings[holding_id] = holding unless holding_id.nil? || (!is_alma && invalid_location?(holding['location_code']))`

2021-02-17 15:52 UTC, christinach commented on spec/marc_to_solr/lib/princeton_marc_spec.rb
> +    xit 'excludes holdings with an invalid location code' do
Ok, I will update the spec customizing the new fixture.

2021-02-17 16:49 UTC, christinach commented
@hackartisan can you review again?

2021-02-17 17:49 UTC, christinach commented
> @christinach this will need to be rebased on the alma branch, since Monday happened.
> 
> I tried it out and I see a bunch of holdings locations coming through. I also see a bunch that say "no holdings available for this record". I'm not sure what those mean. But this does seem like progress! Here's a screenshot from my local orangelight:
> 
> ![Screen Shot 2021-02-15 at 1 46 35 PM](https://user-images.githubusercontent.com/845363/107983772-7f81fb80-6f94-11eb-9f16-8e351e980c5b.png)

The one that says no holdings available is an electronic record https://princeton.alma.exlibrisgroup.com/ng/page;u=%2Frep%2Faction%2FpageAction.search.mms_results.xml.do%3FxmlFileName%3Dsearch.mms_results.xml&pageViewMode%3DEdit&clear%3Dtrue&pageBean.securityHashToken%3D8857301989828534662
I exported it. It has an 856 : `<datafield tag="856" ind1="4" ind2="0"><subfield code="u">https://ebookcentral.proquest.com/lib/Princeton/detail.action?docID=6135628</subfield></datafield>`

It should display `ebookcentral.proquest.com`. From https://catalog-alma-qa.princeton.edu/catalog/99118919643506421/raw, 
"electronic_access_1display": "{\"https://ebookcentral.proquest.com/lib/Princeton/detail.action?docID=6135628\":[\"ebookcentral.proquest.com\"]}",

This is how it displays in the current catalog https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Acceleration+hours+
![Screen Shot 2021-02-17 at 12 46 28 PM](https://user-images.githubusercontent.com/9905193/108245354-2e9e0e80-711e-11eb-9ca9-315804b4d7da.png)

2021-02-17 18:16 UTC, hackartisan approved these changes

2021-02-17 18:16 UTC, merged