Ensure we encode alma responses as utf-8
pulibrary/marc_liberation pull request #1042
Opened 2021-02-03 16:30 UTC by hackartisan

I wasn't able to replicate the error in a test due to rails' efforts to use utf-8 at all times.

fixes #1041

2021-02-04 15:32 UTC, hectorcorrea requested changes
Anna asked me to add this :) after I suggested using 

```
"mañana".encode(Encoding::ASCII_8BIT)
```

as a test case.

2021-02-04 19:47 UTC, hackartisan commented
@hectorcorrea thanks! after giving this another look I realized I was putting my test in the wrong place; I needed it in the controller to trigger the error because that's where it converts to the xml string. This now has a test and is ready to review if you please.

2021-02-05 13:30 UTC, christinach commented
@hectorcorrea does the updated PR satisfy your requested changes?

2021-02-05 13:30 UTC, christinach approved these changes

2021-02-05 14:11 UTC, hectorcorrea approved these changes

2021-02-05 14:12 UTC, merged