Added inline comments about dump types to yml file
pulibrary/marc_liberation pull request #1051
Opened 2021-02-04 22:09 UTC by hackartisan

refs #1038

@christinach I put in these comments in the context of alma; several of these won't be used any more and there will be a less complexity in the interactions of these dumps. I think this might be sufficient to close #1038; what do you think?

2021-02-04 22:58 UTC, eliotjordan approved these changes

2021-02-05 13:25 UTC, christinach requested changes
@hackartisan thank you for adding the comments. Yes we can close https://github.com/pulibrary/marc_liberation/issues/1038 after merging this PR.

2021-02-05 13:25 UTC, christinach commented on config/marc_liberation.yml
>    constant: 'PRINCETON_RECAP'
Can we be more specific by saying: used for Princeton records we send to SCSB

2021-02-05 13:25 UTC, christinach commented on config/marc_liberation.yml
>    constant: 'PARTNER_RECAP'
Can we also update to: used for records we get from SCSB partners (NYPL and Columbia)

2021-02-05 13:45 UTC, hackartisan commented
@christinach I made those changes. thanks!

2021-02-05 13:49 UTC, christinach approved these changes

2021-02-05 13:55 UTC, merged