Refactor availability controller
pulibrary/marc_liberation pull request #795
Opened 2020-09-17 17:30 UTC by hackmastera

This is a refactor pulling business logic out of the availability controller, moving it with its tests to a `VoyagerLookup` class.

This is work toward making space for the alma side of this functionality, as well as being a step toward #266.

Available for review now or I can work on top of this to get 266 implemented; it just seemed like it might be nice to get it in sooner rather than later.

2020-09-17 19:12 UTC, carolyncole approved these changes
@hackmastera It was hard to determine if your changes had broken anything since the tests were also changed so drastically.  I went ahead and reverted your changes to the controller test and was happy to say they all still passed.  Looks good to me.  I will not merge since @christinach wants to review.

2020-09-17 20:03 UTC, hackmastera commented
> @hackmastera It was hard to determine if your changes had broken anything since the tests were also changed so drastically. I went ahead and reverted your changes to the controller test and was happy to say they all still passed. Looks good to me. I will not merge since @christinach wants to review.

Awesome; thank you for double-checking.

2020-09-17 20:41 UTC, christinach requested changes
It looks great. I added some comments.

2020-09-17 20:41 UTC, christinach commented on spec/models/voyager_lookup_spec.rb
> +      it 'returns a status of online' do
This should say `elf1` not `elf`

2020-09-18 09:51 UTC, christinach commented on spec/models/voyager_lookup_spec.rb
> +      allow(VoyagerHelpers::Liberator).to receive(:get_availability).and_return(bib_id => {})
This could also be added in a different PR.

2020-09-18 14:10 UTC, hackmastera commented
@christinach thanks for the review; I believe I've addressed the comments. ready for another look.

2020-09-18 14:14 UTC, merged