Poll SQS and create full dump events
pulibrary/marc_liberation pull request #959
Opened 2021-01-05 14:23 UTC by hackartisan

2021-01-07 17:25 UTC, tpendragon requested changes
Just a couple small questions. All in all, looks great! These aren't really blockers, just requesting changes so they're looked at, if you decide not to fix them just say so and I'll change to approve.

2021-01-07 17:25 UTC, tpendragon commented on app/jobs/alma_full_dump_transfer_job.rb
> +  def perform(dump:, job_id:, type_constant: 'BIB_RECORDS')
Question: Why is `type_constant:` an argument? Is there a case where it might be something else for a full dump transfer job?

2021-01-07 17:25 UTC, tpendragon commented on app/jobs/alma_full_dump_transfer_job.rb
> +    Net::SFTP.start(sftp_host, sftp_username, password: sftp_password) do |sftp|
suggestion: I wonder if extracting this to a little Downloader would make this easier to parse? Something like
```
Downloader.files_for(job_id: job_id).each do |file|
end
```

Not totally necessary, but might make this job easier to parse?

2021-01-07 17:25 UTC, tpendragon commented on app/models/concerns/file_path_generator.rb
> -    File.join(MARC_LIBERATION_CONFIG['data_dir'], "#{Time.now.to_i.to_s}")
:+1: Great!

2021-01-08 16:44 UTC, eliotjordan commented
@tpendragon We implemented your suggestions. Thanks for the review.

2021-01-08 16:49 UTC, tpendragon approved these changes

2021-01-08 16:49 UTC, merged